### ISSUE TITLE
The search for crystal pools

### ISSUE THREAD

**Issue by Pstkraft** [shadsluiter/ExcelExamples#13]
I am still searching for crystal pools data set....someone please help me.?😣😣😣😣

**Comment by Pstkraft** [comment]
I have found it

**Comment by auror4** [comment]
> I am still searching for crystal pools data set....someone please help me.?😣😣😣😣

i can't find it too

**Comment by PunithKrishnamurthy** [comment]
[CrystalPools (1).xlsx](https://github.com/shadsluiter/ExcelExamples/files/13255866/CrystalPools.1.xlsx)
here it is

**Comment by relmi-mary** [comment]
> [CrystalPools (1).xlsx](https://github.com/shadsluiter/ExcelExamples/files/13255866/CrystalPools.1.xlsx) here it is

but it cant be opened or not even working :(
